/**
 * Phase orchestration: analyze → plan → implement → validate → report.
 *
 * Every phase receives the single {@link PipelineRun} context, so no phase ever reaches for a collaborator
 * that was not handed to it. Identity and provenance fields on every artifact written here are host-owned:
 * a model describes what it found, never who it is or what it ran against.
 */

import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { readInventory } from "../indexing/inventory.ts";
import type { UnitStrategy } from "../storage/types.ts";
import { ensureDir, writeTextAtomic } from "../util/json.ts";
import { repoRoot } from "../util/package.ts";
import { checkCoverage } from "../validation/coverage.ts";
import { runGodotHeadless } from "../validation/godotRun.ts";
import {
  persistValidation,
  skippedResult,
  type ValidationResult,
} from "../validation/levels.ts";
import { checkPresentation } from "../validation/presentation.ts";
import { checkStructural } from "../validation/structural.ts";
import { copyTree } from "../workspaces/staging.ts";
import { removeTree } from "../workspaces/workspace.ts";
import { ensurePort, type PipelineRun } from "./pipeline.ts";

import { behavioralCheck } from "./implementPhase.ts";

export async function phaseValidate(run: PipelineRun): Promise<void> {
  const { workspace, repo } = run.options;
  const state = run.state;
  const inventory =
    state.inventory ?? readInventory(workspace.paths.evidenceInventory);
  state.inventory = inventory;
  if (state.units.length === 0) state.units = inventory.units;
  const unitIds = new Set(state.units.map((unit) => unit.id));
  const port = ensurePort(run);
  const inputRevision = `port@${String(repo.currentPortRevision())}`;
  const expectedGodot = {
    expectedVersion: workspace.config.godot.expectedVersion,
    expectedVersionPrefix: workspace.config.godot.expectedVersionPrefix,
  };

  // Level A — every file and unit carries exactly one disposition.
  const strategyDisposition: Record<UnitStrategy, string> = {
    retain_generated: "retained",
    repair_generated: "repaired",
    replace_component: "replaced",
    blocked: "blocked",
  };
  const dispositions: Record<string, string> = {};
  for (const unit of state.units) {
    if (!unit.analysisRequired) {
      dispositions[unit.id] = "deterministic_only";
      continue;
    }
    const record = state.analyses.get(unit.id);
    dispositions[unit.id] =
      record === undefined ? "blocked" : strategyDisposition[record.strategy];
  }
  const fileDispositions: Record<string, string> = {};
  for (const file of inventory.files) {
    if (file.classification === "excluded") {
      fileDispositions[file.path] =
        `excluded(${file.classificationReason.length > 0 ? file.classificationReason : "no reason recorded"})`;
      continue;
    }
    const owner = state.units.find(
      (unit) => unitIds.has(unit.id) && unit.sourcePaths.includes(file.path),
    );
    if (owner === undefined) continue;
    fileDispositions[file.path] = dispositions[owner.id] ?? "blocked";
  }
  const coverage = checkCoverage({
    units: state.units,
    inventory,
    dispositions,
    fileDispositions,
    inputRevision,
  });

  // Level B — structural, against a copy: the converter's own validate writes inside the project it sees.
  const levelB = ensureDir(join(workspace.paths.validation, "level-b"));
  removeTree(levelB);
  mkdirSync(levelB, { recursive: true });
  copyTree(port, levelB);
  const structural = await checkStructural({
    projectPath: levelB,
    godotBinary: state.godotBinary,
    gm2godotCheckout: workspace.config.gm2godot.checkout,
    python: state.python,
    timeoutSeconds: workspace.config.gm2godot.timeoutSeconds,
    reportDir: ensureDir(join(workspace.paths.validation, "level-b-reports")),
    inputRevision,
    repoRoot,
    expectedGodot,
  });

  // Level C — a real headless boot of the port with a generated SceneTree script.
  const levelC = ensureDir(join(workspace.paths.validation, "level-c"));
  removeTree(levelC);
  mkdirSync(levelC, { recursive: true });
  copyTree(port, levelC);
  const bootScript = join(levelC, "tools", "deep_boot.gd");
  writeTextAtomic(
    bootScript,
    [
      "# Generated by gm2godot-deep: boots the project headlessly and exits immediately.",
      "extends SceneTree",
      "",
      "func _initialize() -> void:",
      "\tquit(0)",
      "",
    ].join("\n"),
  );
  const boot: ValidationResult =
    state.godotBinary === null
      ? skippedResult({
          level: "C",
          checkId: "runtime-boot",
          name: "level C runtime — headless boot of the port",
          inputRevision,
          reason: "godot binary not configured or not found",
        })
      : await runGodotHeadless({
          binary: state.godotBinary,
          projectPath: levelC,
          scriptPath: "tools/deep_boot.gd",
          timeoutSeconds: workspace.config.godot.timeoutSeconds,
          logsDir: ensureDir(join(workspace.paths.validation, "logs")),
          checkId: "runtime-boot",
          inputRevision,
          level: "C",
          name: "level C runtime — headless boot of the port",
          expectedGodot,
        });

  const behavioral = await behavioralCheck(run, {
    candidateProjectDir: port,
    workspaceValidationDir: join(workspace.paths.validation, "behavioral"),
    checkId: "behavioral-trace",
    inputRevision,
  });

  const presentation = checkPresentation({
    projectPath: port,
    godotBinary: state.godotBinary,
    hasAudioDevice: false,
    exportTemplateInstalled: false,
    inputRevision,
  });

  const results: ValidationResult[] = [
    coverage,
    ...structural,
    boot,
    behavioral,
    ...presentation,
  ];
  persistValidation({ dir: workspace.paths.evidenceValidation, repo }, results);
  for (const result of results) {
    if (result.state === "skipped")
      run.skipped.push(`${result.checkId}: ${result.reason ?? "skipped"}`);
    else if (result.state === "failed")
      run.failed.push(`${result.checkId}: ${result.reason ?? "failed"}`);
    else if (result.state === "inconclusive")
      run.skipped.push(
        `${result.checkId}: inconclusive — ${result.reason ?? "no reason"}`,
      );
  }
  run.options.logger.info(
    `validate: ${String(results.filter((result) => result.state === "passed").length)} passed, ${String(results.filter((result) => result.state === "failed").length)} failed, ${String(results.filter((result) => result.state === "skipped").length)} skipped`,
  );
}
